- hosts: localhost
  tasks:
    - name: download nessus agent from s3
      shell: aws s3 cp --region us-east-1 s3://jhc-jeff/NessusAgent-6.10.9-es7.x86_64.rpm /tmp

    - name: install nessus agent
      yum:
       name: /tmp/NessusAgent-6.10.9-es7.x86_64.rpm
       state: present

    - name: join the agent to a master
      shell: /opt/nessus_agent/sbin/nessuscli agent link -- key=00b5a8fec9f3a21fa1cff66ce99c6324adf324226948c6f1516eb9f9433b964744

    - name: verify the join was successful
      shell: /opt/nessus_agent/sbin/nessuscli agent status